version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: chatbot_postgres
    restart: always
    environment:
      POSTGRES_USER: chatbot
      POSTGRES_PASSWORD: chatbot123
      POSTGRES_DB: chatbotdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: chatbot_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Optional: pgAdmin (GUI for Postgres)
  pgadmin:
    image: dpage/pgadmin4
    container_name: chatbot_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

volumes:
  postgres_data:
  redis_data:
